name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'microsoft'
        
    - name: Install zowe cli
      run:  npm install -g @zowe/cli@latest

    - name: Create zowe profile
      run: zowe profiles create zosmf-profile myprofile --host 204.90.115.200 --port 10443 --user ${{ secrets.ZOWE_USERNAME }} --password ${{ secrets.ZOWE_PASSWORD }}

    - name: Setup Mainframe environment
      run: |
        chmod +x .github/scripts/zowe_operations.sh
        .github/scripts/zowe_operations.sh
